[package]
name = "entity"
version = "0.0.0"
author = ["Rintaro Itokawa<me@re-taro.dev>"]
edition = "2021"
description = "API entity"
homepage = "https://github.com/re-taro-dev/api.re-taro.dev#README"
repository = "https://github.com/re-taro-dev/api.re-taro.dev"

[dependencies]
